version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: converter
    container_name: converter
    restart: unless-stopped
    stdin_open: true  # Позволяет открывать стандартный ввод
    tty: true         # Позволяет использовать терминал
